// <auto-generated />
using ERMSAPI.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ERMSAPI.Migrations
{
    [DbContext(typeof(ERMSContext))]
    partial class ERMSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ERMSAPI.Models.Users", b =>
                {
                    b.Property<string>("username")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("username");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
